name: "Setup orbit"
author: "Chase Ruskin"
branding:
  icon: 'play'
  color: 'blue'
description: Install the orbit HDL package manager
inputs:
  orbit-version:
    description: 'A valid semver specifier of the orbit version to install'
    required: false
    default: null
    
runs:
  using: "composite"
  steps:
    - if: ${{ inputs.orbit-version }} == null
      name: Install orbit from remote repository using latest version
      uses: baptiste0928/cargo-install@v3
      with:
        crate: orbit
        git: https://github.com/chaseruskin/orbit

    - if: ${{ inputs.orbit-version }} != null
      name: Install orbit from remote repository using particular version
      uses: baptiste0928/cargo-install@v3
      with:
        crate: orbit
        git: https://github.com/chaseruskin/orbit
        tag: ${{ inputs.orbit-version }}