name: Release
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for release'
        required: true
        type: string
      major:
        description: 'Major version tag'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Repository
      uses: actions/checkout@v4

    - name: Display filesystem contents
      run: ls -R

    - name: Validate release notes
      run: ./scripts/autocl.py ${{ inputs.version }}

    - name: Write release notes
      run: echo "$(./scripts/autocl.py ${{ inputs.version }})" > ./RELEASE_NOTES.md

    - name: Tag commit as version
      run: git tag ${{ inputs.version }}

    - name: Push specific version tag
      run: git push --tags

    - name: Move major version tag
      shell: bash {0}
      run: |
        git tag -d ${{ inputs.major }}
        git push origin :refs/tags/${{ inputs.major }}
        git tag ${{ inputs.major }}
        git push --tags
      
    - name: Upload releases
      uses: ncipollo/release-action@v1
      with:
        bodyFile: ./RELEASE_NOTES.md
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ inputs.version }}

  post-release-latest:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Orbit
        uses: chaseruskin/setup-orbit@dev

      - name: Test Orbit
        run: orbit --version

  post-release-specific:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Orbit
        uses: chaseruskin/setup-orbit@dev
        with:
          orbit-version: 0.12.0

      - name: Test Orbit
        run: orbit --version